"""
Real pull-request creation.

Replaces the previous stub, which returned a hard-coded
https://github.com/your-org/your-repo/pull/999 regardless of what happened.
"""
from __future__ import annotations

import base64
from dataclasses import dataclass
from datetime import datetime, timezone

import structlog
from github import Auth, Github, GithubException

from cloudforge.core.git.workspace import RepoRef, parse_repo_url

log = structlog.get_logger()


class PullRequestError(RuntimeError):
    """Raised when a pull request cannot be opened."""


@dataclass
class PullRequestResult:
    url: str
    branch: str
    base: str
    files: list[str]


def _slugify(text: str, limit: int = 40) -> str:
    cleaned = "".join(c if c.isalnum() or c in "-_" else "-" for c in text.lower())
    while "--" in cleaned:
        cleaned = cleaned.replace("--", "-")
    return cleaned.strip("-")[:limit] or "update"


def open_pull_request(
    repo_url: str,
    files: list[dict],
    title: str,
    token: str,
    body: str | None = None,
    base: str | None = None,
) -> PullRequestResult:
    """Commit `files` to a new branch and open a PR against the base branch."""
    if not token:
        raise PullRequestError(
            "No GitHub token available. Set GITHUB_TOKEN or pass github_token on the run."
        )
    if not files:
        raise PullRequestError("No files to commit.")

    ref: RepoRef = parse_repo_url(repo_url)
    gh = Github(auth=Auth.Token(token))

    try:
        repo = gh.get_repo(ref.full_name)
    except GithubException as exc:
        raise PullRequestError(
            f"Cannot access {ref.full_name}: {exc.data.get('message', exc.status) if exc.data else exc.status}"
        ) from exc

    base_branch = base or repo.default_branch
    try:
        base_sha = repo.get_branch(base_branch).commit.sha
    except GithubException as exc:
        raise PullRequestError(f"Base branch '{base_branch}' not found: {exc}") from exc

    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    branch = f"cloudforge/{_slugify(title)}-{stamp}"

    try:
        repo.create_git_ref(ref=f"refs/heads/{branch}", sha=base_sha)
    except GithubException as exc:
        raise PullRequestError(f"Could not create branch '{branch}': {exc}") from exc

    committed: list[str] = []
    for f in files:
        path = f["path"]
        content = f.get("content", "")
        message = f"cloudforge: {path}"
        try:
            existing = repo.get_contents(path, ref=branch)
            sha = existing.sha if not isinstance(existing, list) else None
            if sha is None:
                raise PullRequestError(f"'{path}' is a directory in the target repo")
            repo.update_file(path, message, content, sha, branch=branch)
        except GithubException as exc:
            if exc.status != 404:
                raise PullRequestError(f"Failed writing '{path}': {exc}") from exc
            repo.create_file(path, message, content, branch=branch)
        committed.append(path)

    pr_body = body or _default_body(files)
    try:
        pr = repo.create_pull(title=title, body=pr_body, head=branch, base=base_branch)
    except GithubException as exc:
        raise PullRequestError(f"Could not open PR: {exc}") from exc

    log.info("github.pr_opened", repo=ref.full_name, branch=branch, url=pr.html_url)
    return PullRequestResult(url=pr.html_url, branch=branch, base=base_branch, files=committed)


def _default_body(files: list[dict]) -> str:
    lines = [
        "Generated by [CloudForge](https://forc.cariara.com).",
        "",
        "### Files",
    ]
    for f in files:
        scans = []
        for key, label in (("checkov", "checkov"), ("tfsec", "tfsec"),
                           ("actionlint", "actionlint"), ("pint", "pint")):
            data = f.get(key) or {}
            if not isinstance(data, dict) or "passed" not in data:
                continue
            if data.get("skipped"):
                scans.append(f"{label}: skipped")
            else:
                scans.append(f"{label}: {'pass' if data['passed'] else 'FAIL'}")
        suffix = f" — {', '.join(scans)}" if scans else ""
        lines.append(f"- `{f['path']}`{suffix}")
    lines += ["", "Review the plan output before merging."]
    return "\n".join(lines)
